
-- INSERT DATA DOCUMENT IN  DATABASE MYSQL OF NAME "contato"
INSERT INTO  contato.DOCUMENTS  (  id, RG, CPF	) VALUES (	NULL, "99924135013", "243599203" );
INSERT INTO  contato.DOCUMENTS  (  id, RG, CPF	) VALUES (	NULL, "97724135013", "243577203" );
INSERT INTO  contato.DOCUMENTS  (  id, RG, CPF	) VALUES (	NULL, "96624135013", "243566203" );

-- INSERT DATA ADDRESS IN  DATABASE MYSQL OF NAME "contato"
INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS ) VALUES ( NULL, "São Paulo", "Rua xxx", "RESIDENCIAL" );
INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS ) VALUES ( NULL, "São Paulo", "Rua yyy", "COMERCIAL" );

INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS) VALUES (	NULL, "Pouso Alegre", "Rua aaa", "RESIDENCIAL");
INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS) VALUES (	NULL, "Pouso Alegre", "Rua bbb", "COMERCIAL");

INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS) VALUES (	NULL, "Registro", "Rua ccc", "RESIDENCIAL");
INSERT INTO  contato.ADDRESSES  (  ID_ADDRESS, CITY, STREET, TYPE_ADDRESS) VALUES (	NULL, "Registro", "Rua ddd", "COMERCIAL");


-- INSERT DATA PERSON IN  DATABASE MYSQL OF NAME "contato"
-- TODO: Consultar ID na tabela DOCUMENTS
INSERT INTO  contato.PERSONS  (  ID_PERSON, FIRST_NAME, LAST_NAME, AGE, DOCUMENT_ID) VALUES  ( NULL, "Tiago", "Tibães", 37, 1);
INSERT INTO  contato.PERSONS  (  ID_PERSON, FIRST_NAME, LAST_NAME, AGE, DOCUMENT_ID) VALUES  ( NULL, "Rogério", "Tibães", 50, 2);
INSERT INTO  contato.PERSONS  (  ID_PERSON, FIRST_NAME, LAST_NAME, AGE, DOCUMENT_ID) VALUES  ( NULL, "Didier", "Miranda", 29, 3);

-- INSERT DATA PHONE IN  DATABASE MYSQL OF NAME "contato"
-- TODO: Consultar ID na tabela PERSONS
INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "RESIDENCIAL", "3445-3445", 1 );
INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "COMERCIAL", "3445-3335", 1 );

INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "CELULAR", "98735-5547", 2 );
INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "COMERCIAL", "2445-2225", 2 );

INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "CELULAR", "98835-5548", 3 );
INSERT INTO  contato.PHONES  (  ID_PHONE, TYPE_PHONE, PHONE_NUMBER, PERSON_ID  ) VALUES (	NULL, "COMERCIAL", "2115-2215", 3 );


-- INSERT DATA PERSONS_ADDRESSES IN  DATABASE MYSQL OF NAME "contato"
-- TODO: Consultar ID nas tabelas PERSONS e ADDRESSES
INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (1, 1 );
INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (2, 1 );

INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (2, 2 );
INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (3, 2 );

INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (4, 3 );
INSERT INTO  contato.PERSONS_ADDRESSES  (  ID_ADDRESS, ID_PERSON) VALUES (5, 3 );
			







